// https://docs.expo.dev/guides/using-eslint/
const { defineConfig } = require('eslint/config');
const expoConfig = require('eslint-config-expo/flat');

module.exports = defineConfig([
  expoConfig,
  {
    ignores: [
      'dist/*',
      '.expo/*',
      '.expo-smoke/*',
      'node_modules/*',
      // Generated by `npm run db:types`.
      'src/lib/database.types.ts',
    ],
  },
  {
    rules: {
      // The ledger must never be compared loosely — money bugs hide in coercion.
      eqeqeq: ['error', 'always'],
      'no-console': ['warn', { allow: ['warn', 'error'] }],
    },
  },
  {
    // Must come AFTER the general rules: in flat config the last matching block
    // wins, so placing this first would silently have no effect.
    // Scripts run in Node, not the app — printing to stdout is the whole point.
    files: ['scripts/**/*'],
    rules: { 'no-console': 'off' },
  },
]);
