/**
 * What a report looks like as text, before anything decides where it goes.
 *
 * Kept apart from `export.ts` so the phone and the browser, which get a file
 * out in completely different ways, share one idea of what the file contains.
 */

/** RFC 4180: quote anything containing a comma, quote or newline; double the quotes. */
function csvCell(value: string | number | null | undefined): string {
  const text = value === null || value === undefined ? '' : String(value);
  if (/[",\n\r]/.test(text)) return `"${text.replace(/"/g, '""')}"`;
  return text;
}

export function toCsv(headers: string[], rows: (string | number | null)[][]): string {
  // A BOM, so Excel opens ₵ and any non-ASCII name as UTF-8 rather than
  // mojibake. Without it a member called "Yaw Owusu-Ansah" is fine but a
  // currency symbol is not, and the treasurer blames the app.
  return (
    '﻿' +
    [headers.map(csvCell).join(','), ...rows.map((row) => row.map(csvCell).join(','))].join('\r\n')
  );
}

/** Filesystem-safe, and still recognisable in a downloads folder. */
export function safeName(name: string): string {
  return name
    .replace(/[^a-zA-Z0-9-_ ]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .slice(0, 60);
}

/**
 * A print stylesheet that assumes nothing about the viewer.
 *
 * Deliberately plain: system fonts, no colour that matters, no external asset.
 * A PDF that has to fetch a webfont renders differently or not at all depending
 * on when it is opened, and this is a financial record.
 */
export function reportHtml(title: string, subtitle: string, body: string): string {
  return `<!DOCTYPE html><html><head><meta charset="utf-8" />
<style>
  @page { margin: 24px; }
  body { font-family: -apple-system, Roboto, "Helvetica Neue", sans-serif; color: #12211C; font-size: 12px; }
  h1 { font-size: 20px; margin: 0 0 2px; }
  .sub { color: #66756F; font-size: 12px; margin: 0 0 18px; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 18px; }
  th, td { text-align: left; padding: 7px 6px; border-bottom: 1px solid #E3E9E6; }
  th { font-size: 10px; text-transform: uppercase; letter-spacing: .06em; color: #66756F; }
  td.num, th.num { text-align: right; white-space: nowrap; }
  tr.total td { font-weight: 700; border-top: 2px solid #12211C; border-bottom: none; }
  .foot { color: #9AA8A3; font-size: 10px; margin-top: 24px; }
</style></head><body>
<h1>${title}</h1>
<p class="sub">${subtitle}</p>
${body}
<p class="foot">Generated by Kobox on ${new Date().toLocaleString('en-GB')}. Amounts are as recorded in the app.</p>
</body></html>`;
}
